# Generated by Django 5.0.2 on 2024-03-01 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
